repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0  # Oppdatert til nyere versjon
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0  # Oppdatert til nyere versjon
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2  # Oppdatert til nyere versjon
    hooks:
      - id: mypy
        files: ^custom_components/
        exclude: ^tests/
        additional_dependencies:
          - homeassistant>=2025.1.0
          - pydantic>=2.10.0
          - python-socketio>=5.10.0
          - pytest>=8.0.0
          - pytest-homeassistant-custom-component>=0.13.250
        args:
          - --python-version=3.13
          - --show-error-codes
          - --ignore-missing-imports

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args:
          - --ignore-words-list=hass,homestate
          - --skip=*nb.json

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]  # Kjør kun på pre-push, ikke hver commit
